### ISSUE TITLE
大佬救命啊！！！

### ISSUE THREAD

**Issue by yybjy** [XueMeijing/dingtalk-chatgpt-bot#3]
兄弟我昨天更改了我的那个sesstoken,昨天还能用，我今天刷新了一下那个sesstoken,结果就不能用了，一直提示我conservationid错误
大佬就救命啊，这是咋啦，我换了好几个Sesstoken都不管用，一直提示这个错误，昨天还可以用
![屏幕截图 2023-02-07 134946](https://user-images.githubusercontent.com/91821567/217170257-f894db60-2c5a-4b6d-96a7-89b236600d5c.png)

**Comment by yybjy** [comment]
就昨天那个pygpt的项目，昨天还可以用，今天我就改了一下sesstoken就一直报错

**Comment by XueMeijing** [comment]
不知道啥情况呢，你把刷新后的sesstoken复制下？确保你复制的是```__Secure-next-auth.session-token```这里面的值，他有几个长得挺像的。我这里试了下新sesstoken是可以的

另外你可以把原作者仓库的issue关了，I hoping you can tell me 这种语法在外国人看来应该是不太礼貌的，尽量别用
