### ISSUE TITLE
失败

### ISSUE THREAD

**Issue by thechex1** [XueMeijing/dingtalk-chatgpt-bot#5]
![image](https://user-images.githubusercontent.com/74664452/218425967-4b507c16-7dce-4e4e-84ec-e5c24047f0e7.png)

**Comment by XueMeijing** [comment]
看报错感觉是session的问题，看下你复制错了没，叫这个名字```__Secure-next-auth.session-token``` 对应的value值

我本地报错关于isoformat是这个 https://github.com/PawanOsman/PyGPT/issues/12 提到的问题，你要是也这样，先暂时复制一份 [pygpt](https://github.com/PawanOsman/PyGPT/blob/main/src/pygpt.py) 到本地文件夹，把那几行改一下就好了

**Comment by XueMeijing** [comment]
或者你跟那个issue里面的一样，是plus版本的，要等pygpt仓库的作者修复了
