### ISSUE TITLE
请求接口失败，请稍后重试

### ISSUE THREAD

**Issue by cofess** [XueMeijing/dingtalk-chatgpt-bot#7]
大哥，成功部署到服务器了，提示：请求接口失败，请稍后重试

**Comment by XueMeijing** [comment]
> 大哥，成功部署到服务器了，提示：请求接口失败，请稍后重试

你 ```tail -30f nohup.out``` 看下日志怎么说，我刚才试了下还是可以的，失败一般有几种情况，token过期，一个小时内请求次数过多限制了，要是plus版本要加另外的参数，或者就是 https://github.com/PawanOsman/PyGPT 这个作者正在更新服务器，不过一般不会。目前版本还没有支持上下文，我正在调试加sqlite数据库支持，但是最近太忙先放着了

**Comment by XueMeijing** [comment]
最近有在用吗，刚更新了上下文功能感兴趣了可以试试看，要是没问题我就关掉issue了
