### ISSUE TITLE
Connection refused by the server

### ISSUE THREAD

**Issue by relei1988** [XueMeijing/dingtalk-chatgpt-bot#9]
已经成功对话n轮，大约5分钟后钉钉开始显示`请求接口失败 请稍后重试`

根据后台记录
```
....
 'text': {'content': '可以开始对话了吗'}, 'robotCode': 'ding2g***', 'msgtype': 'text'}
签名验证成功-----
retry_count 1
error
 ConnectionError('Connection refused by the server')
retry_count 2
error
 ConnectionError('Connection refused by the server')
retry_count 3
```
可能是询问较为频繁，是否有时间间隔限制或者推荐？

**Comment by XueMeijing** [comment]
gpt的请求报错不是这样的，感觉可能是 [作者](https://github.com/PawanOsman/PyGPT) 的代理服务器有点什么问题？
你可以 /reset打开新聊天看看，我昨天也是，reset之后正常了但是没有继续测试。你试下如果再正常之后再一段时间就不行了，我感觉很可能是一个聊天上下文太长了，代理服务器有长度限制，因为之前没有上下文，我加了sql存了聊天id才可以

**Comment by relei1988** [comment]
超长应该不会，其实也不长，/reset了没用，但是放了一会又能用了，也是神奇

**Comment by XueMeijing** [comment]
🥲我有空测试一下是什么问题
你也可以fork修改一下试试3.5的能力？应该换掉那几行gpt请求的代码就好了
https://platform.openai.com/docs/models/gpt-3-5
https://platform.openai.com/docs/libraries/python-library

**Comment by relei1988** [comment]
3.5我已经试过了，与网页版比差距挺大的

**Comment by XueMeijing** [comment]
我在discord问了作者，他说每个ip限制50个链接，或者有速率限制，超过之后会拉黑1-5分钟，感觉可能是这个问题导致的。我代码有点小问题，有空改一下试试效果
![image](https://user-images.githubusercontent.com/35559153/223468496-4633727b-f047-4ac6-8fb6-519d6a121882.png)
![image](https://user-images.githubusercontent.com/35559153/223468857-053ed4aa-084c-40c1-a077-ebae316f0fcb.png)

**Comment by relei1988** [comment]
哦他的意思是一个ip给50个connections？那我肯定没的，看后台有两个connected 就不错了，应该是其他原因吧。

**Comment by XueMeijing** [comment]
我代码有点问题，每次http请求会重新生成一个链接，他最后说 ```or connect many times in a short time it will block you for 1-5 mins ```, 也有速率限制吧，总之我改完代码再试试看

**Comment by relei1988** [comment]
好的原来如此，期待新版本。

**Comment by XueMeijing** [comment]
更新了，你可以试试看，我上午二十多分钟试了十几条都是正常的。另外它有时候会提示你检查session是否过期，重新请求有时候又能请求了，如果几次还不行可能就是真过期需要更新session了。
要是有其他问题欢迎随时联系

**Comment by relei1988** [comment]
多谢，等下更新下测试了给反馈哈。

**Comment by relei1988** [comment]
> 更新了，你可以试试看，我上午二十多分钟试了十几条都是正常的。另外它有时候会提示你检查session是否过期，重新请求有时候又能请求了，如果几次还不行可能就是真过期需要更新session了。 要是有其他问题欢迎随时联系

DOCKER还没上传对吧。。怪不得没拉到，如果准备上传的话我再等等哈哈

**Comment by XueMeijing** [comment]
我的，忘了打包docker了😓 你试试看
docker run -dp 8083:8083 fengcailing/dingtalk-chatgpt-bot:1.0.2

**Comment by relei1988** [comment]
新的报错为：
```
签名验证成功-----
retry_count 1
error
 BadNamespaceError('/ is not a connected namespace.')
retry_count 2
error
 BadNamespaceError('/ is not a connected namespace.')
retry_count 1
error
 ConnectionError('Connection refused by the server')
retry_count 2
error
 ConnectionError('Connection refused by the server')
retry_count 3
error
 ConnectionError('Connection refused by the server')
retry_count 3
error
 BadNamespaceError('/ is not a connected namespace.')
```
不过我启动依然用的
`docker run -dp 8083:8083 dingtalk-chatgpt-bot:v1`
命令，如果用
`docker run -dp 8083:8083 fengcailing/dingtalk-chatgpt-bot:1.0.2`
会丢失config.py内容

**Comment by XueMeijing** [comment]
我对docker不太熟，这两个是不同的镜像吧？这次顺便也更新了数据库的字段名称，要不你试试用1.0.2的，就是需要更新config.py的配置然后重新保存成新的镜像

**Comment by relei1988** [comment]
重新部署后目前已经可以稳定运行了。docker主要是不用在一python各种包的潜在影响，还是挺好用的。辛苦大佬。
